openapi: 3.0.0
info:
  title: ModernStore Products API
  version: 1.0.0
  description: API for ecommerce store for managing products
servers:
  - url: http://localhost:8080/api
paths:
  /test:
    get:
      tags:
        - test
      operationId: testEndpoint
      summary: Test endpoint
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
