openapi: 3.0.0
info:
  title: ModernStore API
  version: 1.0.0
  description: API for ecommerce store
servers:
  - url: http://localhost:8080/api
paths:
  /products:
    get:
      tags:
        - products
      operationId: getAllProducts
      summary: Get all products
      parameters:
        - name: category
          in: query
          description: Filter products by category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /products/{id}:
    get:
      tags:
        - products
      operationId: getProductById
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /products/find-by-ids:
    post:
      tags:
        - products
      operationId: getProductsByIds
      summary: Get products by a list of IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/wishlist:
    get:
      tags:
        - users
      operationId: getUserWishlist
      summary: Get user's wishlist
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/wishlist/{productId}:
    post:
      tags:
        - wishlist
      operationId: addItemToUserWishlist
      summary: Add item to user's wishlist
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to add
          required: true
          schema:
            type: string
      responses:
          '201':
            $ref: '#/components/responses/Created'
          '400':
            $ref: '#/components/responses/BadRequest'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '404':
            $ref: '#/components/responses/NotFound'
          '5XX':
            $ref: '#/components/responses/Unexpected'
    delete:
      tags:
        - wishlist
      operationId: removeItemFromUserWishlist
      summary: Remove item from user's wishlist
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to remove
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/wishlist/clear:
    delete:
      tags:
        - wishlist
      operationId: clearUserWishlist
      summary: Clear user's wishlist
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/cart:
    get:
      tags:
        - users
      operationId: getUserCart
      summary: Get user's shopping cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItemDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/cart/{productId}:
    post:
      tags:
        - users
      operationId: addItemToUserCart
      summary: Add item to user's shopping cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
              type: string
        - name: productId
          in: path
          description: ID of the product to add
          required: true
          schema:
              type: string
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      tags:
        - users
      operationId: removeItemFromUserCart
      summary: Remove item from user's shopping cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to remove
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/cart/{productId}/add:
    post:
      tags:
        - cart
      operationId: addNewProductToCart
      summary: Add mew product to user's shopping cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to increment
          required: true
          schema:
            type: string
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/cart/{productId}/clear:
    delete:
      tags:
        - cart
      operationId: clearUserCartItem
      summary: Clear all quantities of a specific item from user's shopping cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to clear
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/cart/{productId}/move-to-wishlist:
    put:
      tags:
        - users
      operationId: moveItemFromCartToWishlist
      summary: Move item from user's cart to wishlist
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of the product to move
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /users/{userId}/wishlist/move-to-cart:
    put:
      tags:
        - users
      operationId: moveItemsFromWishlistToCart
      summary: Move item from user's wishlist to cart
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductDto'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
components:
  schemas:
    ProductDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        imageUrl:
          type: string
        rating:
          type: number
          format: float
        reviewCount:
          type: integer
        inStock:
          type: boolean
        category:
          $ref: '#/components/schemas/ProductCategoryEnum'
    ProductCategoryEnum:
      type: string
      enum:
        - ELECTRONICS
        - CLOTHING
        - ACCESSORIES
        - HOME
    CartItemDto:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/ProductDto'
        quantity:
          type: integer
  responses:
    Unauthorized:
      description: Access token is missing or invalid
    BadRequest:
      description: The request could not be understood or was missing required parameters
    NotFound:
      description: Resource not found
    Unexpected:
      description: An unexpected error occurred
    Created:
      description: Resource successfully created
    Ok:
      description: Successful operation